version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla-dev
    ports:
      - "9042:9042"  # CQL port
      - "9160:9160"  # Thrift port
      - "10000:10000"  # REST API port
    volumes:
      - scylla-dev-data:/var/lib/scylla
    environment:
      - SCYLLA_BATCH_SIZE_WARN_THRESHOLD_IN_KB=5
      - SCYLLA_BATCH_SIZE_FAIL_THRESHOLD_IN_KB=50
    command: >
      --developer-mode=1
      --smp 1
      --memory 1G
      --overprovisioned 1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - dev-network

  scylla-load-keyspace:
    image: scylladb/scylla:5.2
    depends_on:
      scylla:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "cqlsh", "scylla", "-e",
      "CREATE KEYSPACE IF NOT EXISTS userjwt_dev WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}; 
       USE userjwt_dev; 

       CREATE TABLE IF NOT EXISTS userjwt_dev.users (
         id UUID PRIMARY KEY, 
         username text, 
         email text, 
         password text, 
         active boolean, 
         email_verified boolean,
         roles set<UUID>
       ); 

       CREATE INDEX IF NOT EXISTS ON userjwt_dev.users (username); 
       CREATE INDEX IF NOT EXISTS ON userjwt_dev.users (email); 

       CREATE TABLE IF NOT EXISTS userjwt_dev.roles (
         id UUID PRIMARY KEY, 
         name text
       ); 

       CREATE INDEX IF NOT EXISTS ON userjwt_dev.roles (name); 

       CREATE TABLE IF NOT EXISTS userjwt_dev.refresh_tokens (
         token text PRIMARY KEY, 
         user_id UUID, 
         expires_at timestamp, 
         revoked boolean
       ); 

       CREATE INDEX IF NOT EXISTS ON userjwt_dev.refresh_tokens (user_id); 
       CREATE INDEX IF NOT EXISTS ON userjwt_dev.refresh_tokens (expires_at); 

       INSERT INTO userjwt_dev.roles (id, name) VALUES (6e2ee760-0100-47a1-b5bc-e22797fc05fb, 'ROLE_ADMIN') IF NOT EXISTS; 
       INSERT INTO userjwt_dev.roles (id, name) VALUES (8858c5c5-35bc-4fd2-8949-5f6de9444a78, 'ROLE_USER') IF NOT EXISTS;" ]
    networks:
      - dev-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - dev-network

  # Redis for caching/sessions
  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  scylla-dev-data:
    driver: local
  redis-dev-data:
    driver: local